[model_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"

[additional_network_arguments]
no_metadata = false
unet_lr = 0.0001
text_encoder_lr = 5e-5
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
network_train_unet_only = false
network_train_text_encoder_only = false

[optimizer_arguments]
optimizer_type = "AdamW8bit"
learning_rate = 0.0001
max_grad_norm = 1.0
lr_scheduler = "constant"
lr_warmup_steps = 0

[dataset_arguments]
cache_latents = true
debug_dataset = false
vae_batch_size = 4

[training_arguments]
output_dir = "/root/AiProfileAPI/output_dir"
output_name = "lora_trained_model"
save_precision = "fp16"
train_batch_size = 1
max_token_length = 225
mem_eff_attn = false
xformers = true
max_train_epochs = 5
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
gradient_checkpointing = false
gradient_accumulation_steps = 1
mixed_precision = "fp16"
clip_skip = 2
logging_dir = "/root/AiProfileAPI/logs"
log_prefix = "lora_trained_model"
lowram = false
no_half_vae = true

[sample_prompt_arguments]
sample_every_n_epochs = 999999
sample_sampler = "ddim"

[dreambooth_arguments]
prior_loss_weight = 1.0

[saving_arguments]
save_model_as = "safetensors"
