[general]
enable_bucket = true
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1
bucket_reso_steps = 64
bucket_no_upscale = false

[[datasets]]
resolution = 512
min_bucket_reso = 256
max_bucket_reso = 1024
caption_dropout_rate = 0
caption_tag_dropout_rate = 0
flip_aug = false
color_aug = false

  [[datasets.subsets]]
  image_dir = "/root/AiProfileAPI/train_dir"
  num_repeats = 20
