[model_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "/root/AiProfileAPI/api/pretrained_model/chilloutmix_NiPrunedFp16Fix.safetensors"

[additional_network_arguments]
no_metadata = false
unet_lr = 0.0001
text_encoder_lr = 5e-5
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
network_train_unet_only = false
network_train_text_encoder_only = false

[optimizer_arguments]
optimizer_type = "AdamW8bit"
learning_rate = 0.0001
max_grad_norm = 1.0
lr_scheduler = "constant"
lr_warmup_steps = 0

[dataset_arguments]
debug_dataset = false
in_json = "/root/AiProfileAPI/api/config_finetune/meta_lat.json"
train_data_dir = "/root/AiProfileAPI/api/train_data_dir"
dataset_repeats = 40
shuffle_caption = true
keep_tokens = 0
resolution = "512,512"
caption_dropout_rate = 0
caption_tag_dropout_rate = 0
caption_dropout_every_n_epochs = 0
color_aug = false
token_warmup_min = 1
token_warmup_step = 0

[training_arguments]
output_dir = "/root/AiProfileAPI/api/output_dir"
output_name = "chillout_5000_test"
save_precision = "fp16"
save_every_n_epochs = 1
train_batch_size = 1
max_token_length = 225
mem_eff_attn = false
xformers = true
max_train_epochs = 5
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
gradient_checkpointing = false
gradient_accumulation_steps = 1
mixed_precision = "fp16"
clip_skip = 2
logging_dir = "/root/AiProfileAPI/api/logs"
log_prefix = "chillout_5000_test"
lowram = false

[sample_prompt_arguments]
sample_every_n_epochs = 999999
sample_sampler = "ddim"

[saving_arguments]
save_model_as = "safetensors"
